### ISSUE TITLE
403 for Luminous Content

### ISSUE THREAD

**Issue by logan-egbert** [kanjialive/kanji-web-app#17]
Consistently receiving 403 Forbidden responses on the request to Kodansha for the Lumi Waei info.  

```
Request URL:
https://www.kenkyusha.co.jp/collab/KanjiAlive/index.php?book=lumi_waei&method=forward&field=%E6%82%AA
Request Method:
GET
Status Code:
403 Forbidden
Remote Address:
150.60.38.127:443
Referrer Policy:
strict-origin-when-cross-origin
```

**Comment by kintopp** [comment]
Unfortunately, this service was discontinued by Kenkyusha due to people scraping data off their pages.

**Comment by logan-egbert** [comment]
Oh man, that's too bad! 

Might be worth pulling that section though since it's dead.

**Comment by kintopp** [comment]
Yes, it's on the todo list for this summer. It's good that you reminded us.
